create extension if not exists pgcrypto;

create table if not exists public.mom_chat_sessions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  device_id text,
  title text not null default 'MOM',
  model_provider text,
  model_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mom_chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.mom_chat_sessions(id) on delete cascade,
  role text not null check (role in ('system','user','assistant','tool')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.mom_memories (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  session_id uuid references public.mom_chat_sessions(id) on delete set null,
  kind text not null default 'note',
  subject text,
  content text not null,
  truth_state text not null default 'candidate' check (truth_state in ('observed','candidate','confirmed','rejected','superseded','stale')),
  confidence real not null default 0.5 check (confidence >= 0 and confidence <= 1),
  source text,
  supersedes uuid references public.mom_memories(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists mom_chat_messages_session_created_idx on public.mom_chat_messages(session_id, created_at);
create index if not exists mom_memories_owner_state_idx on public.mom_memories(owner_id, truth_state, updated_at desc);

alter table public.mom_chat_sessions enable row level security;
alter table public.mom_chat_messages enable row level security;
alter table public.mom_memories enable row level security;

create policy "mom_sessions_owner_all" on public.mom_chat_sessions
for all to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

create policy "mom_messages_owner_all" on public.mom_chat_messages
for all to authenticated
using (exists (select 1 from public.mom_chat_sessions s where s.id = session_id and s.owner_id = auth.uid()))
with check (exists (select 1 from public.mom_chat_sessions s where s.id = session_id and s.owner_id = auth.uid()));

create policy "mom_memories_owner_all" on public.mom_memories
for all to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());
