import 'discovery_models.dart';
import 'discovery_templates.dart';

class _Topic {
  const _Topic(this.domain, this.key, this.question, this.depth);
  final String domain;
  final String key;
  final String question;
  final int depth;
}

const List<_Topic> _topics = [
  _Topic('orientation', 'when_life_slips', 'When life starts slipping, what usually goes first?', 0),
  _Topic('orientation', 'mom_role', 'What do you most want MOM to be in your corner for?', 0),
  _Topic('orientation', 'reminder_feel', 'What should a useful reminder feel like?', 0),
  _Topic('orientation', 'control_level', 'How much control should MOM take when you are clearly stuck?', 0),
  _Topic('orientation', 'bad_day', 'On a bad day, what kind of help actually lands?', 0),
  _Topic('orientation', 'good_day', 'On a good day, what keeps the day good?', 0),
  _Topic('orientation', 'change_style', 'When you want to change something, how do you usually get moving?', 0),
  _Topic('orientation', 'friction', 'What kind of everyday friction costs you the most?', 0),
  _Topic('orientation', 'being_known', 'What would make you feel like MOM actually knows you?', 0),
  _Topic('orientation', 'setup_depth', 'How much do you want MOM to learn up front versus over time?', 0),

  _Topic('structure', 'daily_plan', 'How much structure makes a day feel easier rather than boxed in?', 1),
  _Topic('structure', 'lists', 'What happens when you make a list?', 1),
  _Topic('structure', 'routines', 'How do routines usually work for you?', 1),
  _Topic('structure', 'mess', 'How much does physical or digital mess affect your brain?', 1),
  _Topic('structure', 'sequence', 'Do you like knowing the exact order of what comes next?', 1),
  _Topic('structure', 'flexibility', 'What happens when a plan changes suddenly?', 1),
  _Topic('structure', 'calendar', 'How naturally do calendars fit into your life?', 1),
  _Topic('structure', 'checklists', 'How do checklists feel when you are under pressure?', 1),
  _Topic('structure', 'rules', 'Do rules help you move or make you push back?', 1),
  _Topic('structure', 'reset', 'When everything gets disorganized, what kind of reset works best?', 1),

  _Topic('task_start', 'boring_task', 'What gets you started on a boring task?', 1),
  _Topic('task_start', 'big_task', 'When a task feels huge, what happens first?', 1),
  _Topic('task_start', 'tiny_task', 'Do tiny tasks get done immediately or somehow become tomorrow\'s problem?', 1),
  _Topic('task_start', 'deadline', 'How much does a deadline change your ability to start?', 1),
  _Topic('task_start', 'first_step', 'How important is having a crystal-clear first step?', 1),
  _Topic('task_start', 'body_double', 'Does having another person nearby make starting easier?', 1),
  _Topic('task_start', 'momentum', 'Once you start, how hard is it to keep momentum?', 1),
  _Topic('task_start', 'switching', 'How hard is switching from one task to another?', 1),
  _Topic('task_start', 'unfinished', 'What usually happens to unfinished tasks?', 1),
  _Topic('task_start', 'reward', 'Do rewards actually help you start things?', 1),

  _Topic('memory', 'objects', 'How often do everyday objects vanish into another dimension?', 1),
  _Topic('memory', 'appointments', 'How reliable is your brain with appointments?', 1),
  _Topic('memory', 'promises', 'How well do you remember things you told someone you would do?', 1),
  _Topic('memory', 'names', 'How sticky are names after you meet someone?', 1),
  _Topic('memory', 'instructions', 'What happens when someone gives you several instructions at once?', 1),
  _Topic('memory', 'ideas', 'What happens to good ideas if you do not capture them immediately?', 1),
  _Topic('memory', 'where_put', 'Do you remember where you put things or reconstruct it later?', 1),
  _Topic('memory', 'future_intent', 'How good is your brain at remembering something at the right future moment?', 1),
  _Topic('memory', 'details', 'Which details tend to stick without effort?', 1),
  _Topic('memory', 'memory_trust', 'How much do you trust your own memory day to day?', 1),

  _Topic('attention', 'focus_depth', 'When something grabs you, how deep can your focus go?', 1),
  _Topic('attention', 'distraction', 'What kind of distraction steals you fastest?', 1),
  _Topic('attention', 'background_noise', 'How does background noise affect concentration?', 1),
  _Topic('attention', 'notifications', 'What do notifications do to your train of thought?', 1),
  _Topic('attention', 'conversation_focus', 'How easy is it to stay with a long conversation?', 1),
  _Topic('attention', 'reading', 'What happens when you read something long?', 1),
  _Topic('attention', 'hyperfocus_exit', 'How easy is it to stop something once you are locked in?', 1),
  _Topic('attention', 'multitask', 'How does multitasking usually go for you?', 1),
  _Topic('attention', 'boredom', 'What does boredom do to your attention?', 1),
  _Topic('attention', 'reentry', 'After an interruption, how easily do you get back into what you were doing?', 1),

  _Topic('time', 'time_sense', 'How accurate is your internal clock?', 1),
  _Topic('time', 'leave_time', 'When you need to leave at a certain time, what usually happens?', 1),
  _Topic('time', 'duration', 'How good are you at guessing how long things will take?', 1),
  _Topic('time', 'future', 'How real does next week feel compared with right now?', 1),
  _Topic('time', 'early', 'How often are you early without trying hard?', 1),
  _Topic('time', 'buffer', 'Do you naturally leave buffer time?', 1),
  _Topic('time', 'time_pressure', 'What does time pressure do to your brain?', 1),
  _Topic('time', 'transition_time', 'Do transitions take longer than you expect?', 1),
  _Topic('time', 'late_pattern', 'If you are late, what is usually the cause?', 1),
  _Topic('time', 'time_reminders', 'What kind of time reminder actually changes your behavior?', 1),

  _Topic('motivation', 'interest', 'How much does interest determine whether something gets done?', 1),
  _Topic('motivation', 'urgency', 'How much does urgency wake your brain up?', 1),
  _Topic('motivation', 'meaning', 'How much easier is work when it feels meaningful?', 1),
  _Topic('motivation', 'competition', 'Does competition energize you or annoy you?', 1),
  _Topic('motivation', 'praise', 'How much does praise affect your motivation?', 1),
  _Topic('motivation', 'accountability', 'What does accountability from another person do for you?', 1),
  _Topic('motivation', 'progress', 'How motivating is visible progress?', 1),
  _Topic('motivation', 'novelty', 'How much does novelty matter?', 1),
  _Topic('motivation', 'consequence', 'Do consequences motivate you before they become immediate?', 1),
  _Topic('motivation', 'identity', 'How much does this is the kind of person I want to be motivate you?', 1),

  _Topic('autonomy', 'being_told', 'What happens inside you when someone tells you what you have to do?', 1),
  _Topic('autonomy', 'choices', 'Do choices help you move or make decisions harder?', 1),
  _Topic('autonomy', 'advice', 'How do you like advice to be offered?', 1),
  _Topic('autonomy', 'nudges', 'How should MOM nudge you without becoming irritating?', 1),
  _Topic('autonomy', 'override', 'When should MOM back off even if she thinks you are making a mistake?', 1),
  _Topic('autonomy', 'permission', 'Do you prefer being asked before MOM takes a helpful action?', 1),
  _Topic('autonomy', 'control', 'How important is feeling like the final call is yours?', 1),
  _Topic('autonomy', 'pressure', 'What kind of pressure makes you resist?', 1),
  _Topic('autonomy', 'suggestions', 'How many suggestions at once feels useful?', 1),
  _Topic('autonomy', 'challenge', 'How should MOM challenge you when she disagrees?', 1),

  _Topic('competence', 'difficulty', 'What happens when something makes you feel incompetent?', 2),
  _Topic('competence', 'learning', 'How do you like learning a new skill?', 2),
  _Topic('competence', 'feedback', 'What kind of feedback helps you improve fastest?', 2),
  _Topic('competence', 'mistakes', 'How do mistakes affect your willingness to keep going?', 2),
  _Topic('competence', 'wins', 'Do small wins matter to you?', 2),
  _Topic('competence', 'instructions', 'How detailed should instructions be when something is new?', 2),
  _Topic('competence', 'practice', 'What makes practice tolerable?', 2),
  _Topic('competence', 'comparison', 'How much do you compare your progress with other people?', 2),
  _Topic('competence', 'confidence', 'What usually gives you confidence to try something?', 2),
  _Topic('competence', 'help_request', 'How easy is asking for help when you do not know something?', 2),

  _Topic('relatedness', 'connection', 'How important is feeling connected to people during the day?', 2),
  _Topic('relatedness', 'checkins', 'How do you feel about people checking in on you?', 2),
  _Topic('relatedness', 'alone', 'How much alone time do you genuinely need?', 2),
  _Topic('relatedness', 'belonging', 'How much does belonging to a group matter to you?', 2),
  _Topic('relatedness', 'shared_task', 'Do you work better when something feels shared?', 2),
  _Topic('relatedness', 'celebration', 'Who do you want to tell when something good happens?', 2),
  _Topic('relatedness', 'support', 'When life is rough, how much do you want another person involved?', 2),
  _Topic('relatedness', 'presence', 'Can simple presence help even when nobody fixes anything?', 2),
  _Topic('relatedness', 'distance', 'What happens when someone important feels distant?', 2),
  _Topic('relatedness', 'team', 'Do you naturally think in terms of me or us?', 2),

  _Topic('social_energy', 'crowds', 'What do crowds do to your energy?', 2),
  _Topic('social_energy', 'small_groups', 'How do small groups feel compared with one-on-one time?', 2),
  _Topic('social_energy', 'new_people', 'What is meeting new people like for you?', 2),
  _Topic('social_energy', 'after_social', 'How do you feel after several hours around people?', 2),
  _Topic('social_energy', 'talking', 'Do you think out loud or think first and then talk?', 2),
  _Topic('social_energy', 'spotlight', 'How does being the center of attention feel?', 2),
  _Topic('social_energy', 'plans', 'How often do social plans sound better earlier than they feel later?', 2),
  _Topic('social_energy', 'strangers', 'How easily do you start conversations with strangers?', 2),
  _Topic('social_energy', 'silence', 'How comfortable is silence with another person?', 2),
  _Topic('social_energy', 'social_recovery', 'What restores you after social overload?', 2),

  _Topic('communication', 'directness', 'How direct do you want MOM to be with you?', 1),
  _Topic('communication', 'length', 'When you ask for help, how much explanation do you usually want?', 1),
  _Topic('communication', 'humor', 'How much humor belongs in serious conversations?', 1),
  _Topic('communication', 'swearing', 'How natural does swearing feel in conversation?', 1),
  _Topic('communication', 'softening', 'Do you want bad news softened or just said plainly?', 1),
  _Topic('communication', 'questions', 'How many follow-up questions feel helpful before it gets annoying?', 1),
  _Topic('communication', 'interruptions', 'When you are talking, how should MOM handle an important interruption?', 1),
  _Topic('communication', 'tone', 'What tone makes advice easiest to hear?', 1),
  _Topic('communication', 'repetition', 'When you miss something, how should MOM repeat it?', 1),
  _Topic('communication', 'misunderstanding', 'If MOM misunderstands you, what repair style feels best?', 1),

  _Topic('emotion', 'feelings_speed', 'How quickly do you usually know what you are feeling?', 3),
  _Topic('emotion', 'intensity', 'How intense do emotions feel when they hit?', 3),
  _Topic('emotion', 'expression', 'How easy is showing people what you are feeling?', 3),
  _Topic('emotion', 'processing', 'Do you process feelings by talking, thinking, doing, or waiting?', 3),
  _Topic('emotion', 'reassurance', 'When upset, how much reassurance helps?', 3),
  _Topic('emotion', 'validation', 'How important is feeling understood before problem-solving starts?', 3),
  _Topic('emotion', 'mood_shift', 'How quickly can your mood shift after something happens?', 3),
  _Topic('emotion', 'carryover', 'How long do emotional moments tend to stay with you?', 3),
  _Topic('emotion', 'naming', 'Does putting a name to a feeling help?', 3),
  _Topic('emotion', 'privacy', 'How private are you with emotions by default?', 3),

  _Topic('stress', 'first_sign', 'What is the first sign that stress is getting high?', 3),
  _Topic('stress', 'overload', 'When overloaded, do you speed up, freeze, shut down, or scatter?', 3),
  _Topic('stress', 'decision_stress', 'What happens to decision-making under stress?', 3),
  _Topic('stress', 'body', 'How much do you notice stress in your body?', 3),
  _Topic('stress', 'sleep', 'What does stress do to your sleep?', 3),
  _Topic('stress', 'irritability', 'How does stress affect your patience?', 3),
  _Topic('stress', 'avoidance', 'When something stressful is waiting, what do you tend to do?', 3),
  _Topic('stress', 'recovery', 'What helps you come back down fastest?', 3),
  _Topic('stress', 'support_under_stress', 'What kind of support feels best when stress is high?', 3),
  _Topic('stress', 'warning', 'Would you want MOM to tell you when she notices a stress pattern building?', 3),

  _Topic('conflict', 'approach', 'When conflict starts, what is your first instinct?', 3),
  _Topic('conflict', 'cooldown', 'Do you need space before talking something through?', 3),
  _Topic('conflict', 'tone_conflict', 'How sensitive are you to tone during disagreement?', 3),
  _Topic('conflict', 'resolution', 'How important is resolving conflict immediately?', 3),
  _Topic('conflict', 'apology', 'What makes an apology feel real to you?', 3),
  _Topic('conflict', 'criticism', 'What happens when you feel criticized?', 3),
  _Topic('conflict', 'fairness', 'How much does fairness matter compared with keeping peace?', 3),
  _Topic('conflict', 'repair', 'What helps you reconnect after an argument?', 3),
  _Topic('conflict', 'boundaries', 'How do you usually handle a crossed boundary?', 3),
  _Topic('conflict', 'mom_conflict', 'If MOM thinks you are rationalizing something, how should she say it?', 3),

  _Topic('attachment_support', 'silence_from_person', 'When someone important goes quiet, what does your brain tend to do?', 3),
  _Topic('attachment_support', 'reassurance_frequency', 'How much reassurance feels comforting instead of excessive?', 3),
  _Topic('attachment_support', 'closeness', 'How much closeness feels natural in important relationships?', 3),
  _Topic('attachment_support', 'space', 'How do you react when someone asks for space?', 3),
  _Topic('attachment_support', 'independence', 'How important is handling problems on your own?', 3),
  _Topic('attachment_support', 'uncertainty', 'How do you handle uncertainty about where you stand with someone?', 3),
  _Topic('attachment_support', 'reach_out', 'When hurt, do you reach out or pull inward?', 3),
  _Topic('attachment_support', 'trust', 'How quickly does trust usually build for you?', 3),
  _Topic('attachment_support', 'repair_after_distance', 'After distance, what helps connection feel real again?', 3),
  _Topic('attachment_support', 'support_boundary', 'When should MOM avoid stepping into relationship worries unless invited?', 3),

  _Topic('openness', 'new_ideas', 'What happens when you hear a weird new idea?', 2),
  _Topic('openness', 'change', 'How do you feel about changing a familiar way of doing something?', 2),
  _Topic('openness', 'art', 'How strongly can music, art, stories, or imagery affect you?', 2),
  _Topic('openness', 'imagination', 'How active is your imagination when nothing else is happening?', 2),
  _Topic('openness', 'abstract', 'How much do you enjoy abstract or philosophical conversations?', 2),
  _Topic('openness', 'experiments', 'How willing are you to try an odd solution just to see if it works?', 2),
  _Topic('openness', 'variety', 'How much variety do you need before routine gets stale?', 2),
  _Topic('openness', 'curiosity', 'How often do you chase a question just because it is interesting?', 2),
  _Topic('openness', 'tradition', 'How much weight do familiar traditions carry for you?', 2),
  _Topic('openness', 'possibility', 'Do possibilities excite you more than certainty comforts you?', 2),

  _Topic('sensory', 'noise', 'How strongly do loud or layered sounds affect you?', 2),
  _Topic('sensory', 'light', 'How much does lighting affect comfort or focus?', 2),
  _Topic('sensory', 'touch', 'How picky is your nervous system about textures or touch?', 2),
  _Topic('sensory', 'crowded_visuals', 'How do visually busy spaces affect you?', 2),
  _Topic('sensory', 'temperature', 'How much does temperature affect your mood or concentration?', 2),
  _Topic('sensory', 'smell', 'How strongly do smells grab your attention?', 2),
  _Topic('sensory', 'phone_haptics', 'How do vibration and haptic alerts feel to you?', 2),
  _Topic('sensory', 'voice_volume', 'What voice volume feels right for MOM?', 2),
  _Topic('sensory', 'notification_sound', 'How noticeable should MOM\'s notification sounds be?', 2),
  _Topic('sensory', 'sensory_recovery', 'What kind of environment helps when everything feels like too much?', 2),

  _Topic('decision', 'speed', 'How quickly do you like making everyday decisions?', 1),
  _Topic('decision', 'options', 'How many options feels like enough without becoming too many?', 1),
  _Topic('decision', 'research', 'How much research do you do before an important choice?', 1),
  _Topic('decision', 'gut', 'How much do you trust your gut?', 1),
  _Topic('decision', 'regret', 'How much do you second-guess decisions afterward?', 1),
  _Topic('decision', 'advice_input', 'How much outside input do you want before choosing?', 1),
  _Topic('decision', 'risk', 'How comfortable are you with uncertain outcomes?', 1),
  _Topic('decision', 'tradeoffs', 'How do you feel about explicitly comparing pros and cons?', 1),
  _Topic('decision', 'small_choices', 'Do tiny choices drain you?', 1),
  _Topic('decision', 'mom_recommendation', 'When MOM has a strong recommendation, how should she present it?', 1),

  _Topic('values_goals', 'important_now', 'What matters most in this season of your life?', 2),
  _Topic('values_goals', 'future_self', 'How often do you think about the person you are becoming?', 2),
  _Topic('values_goals', 'success', 'What makes a day count as successful?', 2),
  _Topic('values_goals', 'relationships_goal', 'How central are relationships to your goals?', 2),
  _Topic('values_goals', 'achievement_goal', 'How central is achievement to your goals?', 2),
  _Topic('values_goals', 'stability_goal', 'How important is stability compared with possibility?', 2),
  _Topic('values_goals', 'growth_goal', 'How important is personal growth even when it is uncomfortable?', 2),
  _Topic('values_goals', 'service_goal', 'How much does helping other people matter in your sense of purpose?', 2),
  _Topic('values_goals', 'freedom_goal', 'How much does freedom matter in your idea of a good life?', 2),
  _Topic('values_goals', 'legacy', 'How much do you care about leaving something behind?', 2),
];

String _lowerFirst(String value) {
  if (value.isEmpty) return value;
  return '${value[0].toLowerCase()}${value.substring(1)}';
}

final List<DiscoveryNode> discoveryBank = _topics.map((topic) {
  final id = '${topic.domain}_${topic.key}';
  return DiscoveryNode(
    id: id,
    domain: topic.domain,
    depth: topic.depth,
    promptVariants: [
      topic.question,
      'Quick gut check: ${_lowerFirst(topic.question)}',
      'No perfect answer here. ${topic.question}',
    ],
    choices: choicesFor(topic.domain, id),
  );
}).toList(growable: false);

final Map<String, DiscoveryNode> discoveryById = {
  for (final node in discoveryBank) node.id: node,
};
